plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.nudgeproof.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'ai.nudgeproof.mobile'
        minSdk 24
        targetSdk 30
        versionCode 450
        versionName '4.5.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix '-stable-logo'
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
